## Version catalog for the Maryk build.
[versions]
android = "9.0.1"
atomicfu = "0.31.0"
benManesVersions = "0.53.0"
compose = "1.7.3"
cryptography = "0.5.0"
kotlin = "2.3.10"
kotlinxCollectionsImmutable = "0.4.0"
kotlinxCoroutines = "1.10.2"
kotlinxDataframe = "0.15.0"
kotlinxDatetime = "0.7.1-0.6.x-compat"
kotter = "1.2.1"
ktor = "3.4.0"
marykFoundationdb = "7.3.73-SNAPSHOT"
marykRocksdb = "10.4.6"
protobuf = "4.33.5"
protobufPlugin = "0.9.6"
protoc = "4.33.5"
versionCatalogUpdate = "1.0.1"
vico = "2.4.3"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "android" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
compose-material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "compose" }
compose-material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "compose" }
cryptography-core = { module = "dev.whyoleg.cryptography:cryptography-core", version.ref = "cryptography" }
cryptography-provider-optimal = { module = "dev.whyoleg.cryptography:cryptography-provider-optimal", version.ref = "cryptography" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-dataframe = { module = "org.jetbrains.kotlinx:dataframe", version.ref = "kotlinxDataframe" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotter = { module = "com.varabyte.kotter:kotter", version.ref = "kotter" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-curl = { module = "io.ktor:ktor-client-curl", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
maryk-foundationdb-multiplatform = { module = "io.maryk.foundationdb:foundationdb-multiplatform", version.ref = "marykFoundationdb" }
maryk-rocksdb-multiplatform = { module = "io.maryk.rocksdb:rocksdb-multiplatform", version.ref = "marykRocksdb" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf" }
protoc = { module = "com.google.protobuf:protoc", version.ref = "protoc" }
vico-multiplatform-m3 = { module = "com.patrykandpatrick.vico:multiplatform-m3", version.ref = "vico" }

[plugins]
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "benManesVersions" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdate" }
