## Version catalog for the Maryk build.
[versions]
android = "8.13.2"
atomicfu = "0.29.0"
benManesVersions = "0.53.0"
kotlin = "2.3.0"
kotlinxCollectionsImmutable = "0.4.0"
kotlinxCoroutines = "1.10.2"
kotlinxDataframe = "0.15.0"
kotlinxDatetime = "0.7.1"
kotter = "1.2.1"
marykFoundationdb = "7.3.73-SNAPSHOT"
marykRocksdb = "10.4.6"
protobuf = "4.33.2"
protobufPlugin = "0.9.6"
protoc = "4.33.2"
versionCatalogUpdate = "1.0.1"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "android" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-dataframe = { module = "org.jetbrains.kotlinx:dataframe", version.ref = "kotlinxDataframe" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotter = { module = "com.varabyte.kotter:kotter", version.ref = "kotter" }
maryk-foundationdb-multiplatform = { module = "io.maryk.foundationdb:foundationdb-multiplatform", version.ref = "marykFoundationdb" }
maryk-rocksdb-multiplatform = { module = "io.maryk.rocksdb:rocksdb-multiplatform", version.ref = "marykRocksdb" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf" }
protoc = { module = "com.google.protobuf:protoc", version.ref = "protoc" }

[plugins]
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "benManesVersions" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdate" }
